version: "3.9"
services:
  sqldata:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=MyComplexPassword123
    ports:
     - "1450:1433"
    networks:
      mynet:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      - RABBITMQ_ERLANG_COOKIE=MyErlangCookie
      - RABBITMQ_DEFAULT_USER=admindocker-compose down --remove-orphans
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      mynet:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: apiserver
    depends_on:
      - sqldata
      - rabbitmq
    ports:
      - "5000:5000"
    networks:
      mynet:
networks:
  mynet:



